name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&count_private=true&theme=omni&hide_border=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=omni&layout=compact&hide_border=true&langs_count=6
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for toebeann/BepInEx.Subnautica
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=BepInEx.Subnautica&theme=omni&hide_border=true
          path: profile/pin-${{ github.repository_owner }}-BepInEx.Subnautica.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for toebeann/gib
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=gib&theme=omni&hide_border=true
          path: profile/pin-${{ github.repository_owner }}-gib.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for toebeann/SnapBuilder
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=SnapBuilder&theme=omni&hide_border=true
          path: profile/pin-${{ github.repository_owner }}-SnapBuilder.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for toebeann/Tobey.UnityAudio
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=${{ github.repository_owner }}&repo=Tobey.UnityAudio&theme=omni&hide_border=true&show_owner=true
          path: profile/pin-${{ github.repository_owner }}-Tobey.UnityAudio.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for SubnauticaModding/QModManager
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=SubnauticaModding&repo=QModManager&theme=omni&hide_border=true&show_owner=true
          path: profile/pin-SubnauticaModding-QModManager.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate pin card for SubnauticaModding/Nautilus
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=SubnauticaModding&repo=Nautilus&theme=omni&hide_border=true&show_owner=true
          path: profile/pin-SubnauticaModding-Nautilus.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate trophy
        uses: ryo-ma/github-profile-trophy
        with:
          username: ${{ github.repository_owner }}
          outpath_path: profile/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: dracula

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
